# Extension VSCODE HTTP Client
@baseUrl = http://localhost:3333
@baseUrlWS = ws://localhost:3333

#create polls
POST {{baseUrl}}/polls
Content-Type: application/json

{
  "title": "Qual o melhor ORM",
  "options": ["PrismaORM", "TypeORM"]
}

###

#get poll
GET {{baseUrl}}/polls/4dd0c288-ea84-436e-96fe-f2f9fcc84cf0
###

#vote on poll
POST {{baseUrl}}/polls/4dd0c288-ea84-436e-96fe-f2f9fcc84cf0/votes
Content-Type: application/json

{
  "pollOptionId": "5b628a17-59f2-49ce-b41e-0a81cf3fb6a8"
}

###
#poll results
GET {{baseUrlWS}}/polls/4dd0c288-ea84-436e-96fe-f2f9fcc84cf0/resuls
###